CREATE TABLE `T_USER` (
	`no` 		INT(11) 	NOT NULL AUTO_INCREMENT,
	`id` 		VARCHAR(30) NOT NULL,
	`pwd` 		VARCHAR(16) NOT NULL,
	`nm` 		VARCHAR(30) NOT NULL,
	`email` 	VARCHAR(100) NOT NULL,
	`phone` 	VARCHAR(11) NULL DEFAULT NULL,
	`delYn` 	VARCHAR(1) NOT NULL DEFAULT 'N',
	`regDate` DATETIME NOT NULL DEFAULT current_timestamp(),
	PRIMARY KEY (`no`)
);
